### ISSUE TITLE
(Feature) Italic text in quotes.

### ISSUE THREAD

**Issue by dru89** [calebegg/pseudocode#1]
For finding failures in quoting, it may be useful to mark things in quotes in some special way.  I'm only mentioning quotes, because it was the first thing that I thought of.  Basically, it would turn this:

System.out.println("\"Test\", he said.");

into this:

System.out.println(“<i>\"Test\", he said.</i>”);

(obviously with proper fonts and stuff).

**Comment by calebegg** [comment]
Perhaps. I was mentally relegating such things to the realm of syntax highlighting, as vim's syntax highlighting can do italics (at least in gvim/macvim). I'll leave this open though and think about it.
